name: Deploy Website to Vercel
on:
  push:
    paths:
      - 'site.zip' # Запускаем только при изменении этого файла

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Extract website files
        run: |
          unzip -o site.zip -d site/
          rm site.zip # Удаляем архив после распаковки

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} \
                 --scope ${{ secrets.VERCEL_ORG_ID }} \
                 --confirm \
                 --prod
        working-directory: ./site
